#ifndef LOCATIONSERVICES_GLOBAL_H
#define LOCATIONSERVICES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOCATIONSERVICES_LIBRARY)
#  define LOCATIONSERVICESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LOCATIONSERVICESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LOCATIONSERVICES_GLOBAL_H
